apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
spec:
  selector:
    app: binyan-playlist-recommender  # 必须和 Deployment 里的 label 一致
  type: LoadBalancer  # 让外部访问
  ports:
    - protocol: TCP
      port: 52005  # 外部访问端口
      targetPort: 52005  # Flask 服务器端口
