apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: binyan
  name: project2-pvc2-binyan
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi 
  volumeName: project2-pv2-binyan
